name: "${project.name}"
main: "${groupId}.DeepDungeons"
version: "${project.version}"
author: emanon
api-version: "1.13"
depend: [ DeepCore ]
softdepend: [ SuperVanish,PremiumVanish,PlaceholderAPI,VirginBlock,Vault,ProtocolLib,CMI,Towny,DracarysGUI,MythicMobs ]