name: DeepDungeons
main: emanondev.deepdungeons.DeepDungeons
version: 1.0
author: emanon
api-version: 1.13
depend: [DeepCore]
softdepend: [SuperVanish,PremiumVanish,PlaceholderAPI,VirginBlock,Vault,ProtocolLib,CMI,Towny,DracarysGUI,MythicMobs]